Repository Zack-Dx/Mini-TODO, pull requests merged in 2022-10, with the labels that each got.

#3 empty note message, scrollbar style, hover on input
  index.html
  index.js
  style.css
Labels: good first issue, hacktober accepted, hacktoberfest, urgent

#8 edit and dark mode theme button added
  index.html
  index.js
  style.css
Labels: hacktober accepted, hacktoberfest, urgent

#16 welcome message added
  .vscode/settings.json
  index.html
  style.css
Labels: urgent

#20 removed commented lines
  index.html
  index.js
Labels: documentation, good first issue, hacktober-accepted, hacktoberfest

#25 feat: Added transitions and UI changes
  index.html
  style.css
Labels: hacktober-accepted, hacktoberfest

#63 Cached UI mode (light / dark) on reload
  index.html
Labels: enhancement, On hold

#87 Enhanced the UI, added "search note" pallet.
  index.html
  index.js
  style.css
Labels: bug

#98 Added some new looks & functions for easy usage
  index.html
  index.js
  style.css
Labels: urgent

#114 Add more functionalities
  .vscode/settings.json
  index.html
  index.js
  style.css
Labels: conflicts

#123 Files structure
  css/style.css
  img/favicon.ico
  img/footer/wave.png
  index.html
  js/index.js
Labels: conflicts
